Feat/basic settings page
digicatapult/veritable-ui pull request #215
Opened 2024-10-28 10:41 UTC by Ellenn-A

# Pull Request

## Checklist
- [x] Have you read Digital Catapult's [Code of Conduct](https://github.com/digicatapult/.github/blob/main/CODE_OF_CONDUCT.md)?
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## PR Type

Please delete options that are irrelevant.

- [ ] Bug Fix
- [ ] Chore
- [x] Feature
- [ ] Documentation Update
- [ ] Code style update (formatting, local variables)
- [ ] Breaking Change (fix or feature that would cause existing functionality to change)

## Linked tickets

https://digicatapult.atlassian.net/browse/VR-248

## High level description

Allows user to view the settings page.

## Detailed description

Settings page with a reset button and the only editable field being the admin email. 

## Describe alternatives you've considered

N/A

## Operational impact

## Additional context

2024-10-30 15:23 UTC, mattdean-digicatapult commented on src/controllers/settings/index.ts
> +  @Post('/update/:edit?')
I'd recommend this just be `/` rather than introducing a verb in the path

2024-10-30 15:29 UTC, mattdean-digicatapult requested changes
This looks really really good. Just a few small changes

2024-10-31 11:43 UTC, jonmattgray commented
Coming to this unfamiliar with the repo so please ignore if I'm wrong. In the video, I'd expect the settings icon in the sidebar to be highlighted when you're on the settings page, it highlights the top icon instead?

2024-10-31 12:30 UTC, jonmattgray commented on test/e2e/helpers/setupConnection.ts
> +  const pinForBob = extractedPin
can delete?

2024-10-31 13:17 UTC, jonmattgray approved these changes

2024-10-31 13:20 UTC, merged